baseURL = "/"
languageCode = "en-us"
title = "New College MCR"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = false # show / hide the contaxt box on the main page
    show_services_button = false  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo.svg"
    mobile_height = "45px"
    desktop = "images/logo/logo.svg"
    desktop_height = "50px"
    alt = "New College MCR"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.team]
    summary_large_truncate = 370  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'New College MCR | Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "MCR Services"
    url = "/services/"
    weight = 1

  [[menu.main]]
    name = "College Life"
    url = "/college/"
    weight = 2

  [[menu.main]]
      name = "Committee"
      url = "/team/"
      weight = 3

  [[menu.main]]
      name = "Useful Links"
      url = "/links/"
      weight = 4

  [[menu.main]]
      name = "Contact"
      url = "/contact_college/"
      weight = 6

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact_college/"
      weight = 2